CREATE TABLE "blackjack_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "blackjack_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "blackjack_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blackjack_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "blackjack_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "blackjack_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "blackjack_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "blackjack_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "blackjack_account" ADD CONSTRAINT "blackjack_account_userId_blackjack_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."blackjack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blackjack_post" ADD CONSTRAINT "blackjack_post_createdById_blackjack_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."blackjack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blackjack_session" ADD CONSTRAINT "blackjack_session_userId_blackjack_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."blackjack_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "blackjack_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "blackjack_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "blackjack_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "blackjack_session" USING btree ("userId");